# Generated by Django 6.0.4 on 2026-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('hackathon', 'Hackathon'), ('social', 'Social'), ('academic', 'Academic'), ('seminar', 'Seminar'), ('other', 'Other')], default='other', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=100, help_text='0 = unlimited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
