/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MyEventsPageRouteImport } from './routes/MyEventsPage'
import { Route as HostPageRouteImport } from './routes/HostPage'
import { Route as ForgotpasswordRouteImport } from './routes/Forgotpassword'
import { Route as EventDetailPageRouteImport } from './routes/EventDetailPage'
import { Route as HostRouteRouteImport } from './routes/Host.route'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsPageRoute = MyEventsPageRouteImport.update({
  id: '/MyEventsPage',
  path: '/MyEventsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const HostPageRoute = HostPageRouteImport.update({
  id: '/HostPage',
  path: '/HostPage',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotpasswordRoute = ForgotpasswordRouteImport.update({
  id: '/Forgotpassword',
  path: '/Forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDetailPageRoute = EventDetailPageRouteImport.update({
  id: '/EventDetailPage',
  path: '/EventDetailPage',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRouteRoute = HostRouteRouteImport.update({
  id: '/Host',
  path: '/Host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Host': typeof HostRouteRoute
  '/EventDetailPage': typeof EventDetailPageRoute
  '/Forgotpassword': typeof ForgotpasswordRoute
  '/HostPage': typeof HostPageRoute
  '/MyEventsPage': typeof MyEventsPageRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Host': typeof HostRouteRoute
  '/EventDetailPage': typeof EventDetailPageRoute
  '/Forgotpassword': typeof ForgotpasswordRoute
  '/HostPage': typeof HostPageRoute
  '/MyEventsPage': typeof MyEventsPageRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Host': typeof HostRouteRoute
  '/EventDetailPage': typeof EventDetailPageRoute
  '/Forgotpassword': typeof ForgotpasswordRoute
  '/HostPage': typeof HostPageRoute
  '/MyEventsPage': typeof MyEventsPageRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Host'
    | '/EventDetailPage'
    | '/Forgotpassword'
    | '/HostPage'
    | '/MyEventsPage'
    | '/explore'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Host'
    | '/EventDetailPage'
    | '/Forgotpassword'
    | '/HostPage'
    | '/MyEventsPage'
    | '/explore'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/Host'
    | '/EventDetailPage'
    | '/Forgotpassword'
    | '/HostPage'
    | '/MyEventsPage'
    | '/explore'
    | '/login'
    | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRouteRoute: typeof HostRouteRoute
  EventDetailPageRoute: typeof EventDetailPageRoute
  ForgotpasswordRoute: typeof ForgotpasswordRoute
  HostPageRoute: typeof HostPageRoute
  MyEventsPageRoute: typeof MyEventsPageRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MyEventsPage': {
      id: '/MyEventsPage'
      path: '/MyEventsPage'
      fullPath: '/MyEventsPage'
      preLoaderRoute: typeof MyEventsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/HostPage': {
      id: '/HostPage'
      path: '/HostPage'
      fullPath: '/HostPage'
      preLoaderRoute: typeof HostPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Forgotpassword': {
      id: '/Forgotpassword'
      path: '/Forgotpassword'
      fullPath: '/Forgotpassword'
      preLoaderRoute: typeof ForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/EventDetailPage': {
      id: '/EventDetailPage'
      path: '/EventDetailPage'
      fullPath: '/EventDetailPage'
      preLoaderRoute: typeof EventDetailPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Host': {
      id: '/Host'
      path: '/Host'
      fullPath: '/Host'
      preLoaderRoute: typeof HostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRouteRoute: HostRouteRoute,
  EventDetailPageRoute: EventDetailPageRoute,
  ForgotpasswordRoute: ForgotpasswordRoute,
  HostPageRoute: HostPageRoute,
  MyEventsPageRoute: MyEventsPageRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
