const events = [
  {
    id: 1,
    title: "Annual Fall Hackathon",
    category: "TECH",
    date: "Oct 24",
    time: "10:00 AM",
    location: "Innovation Hub",
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",
    popular: true,
    liked: false,
    description:
      "Join 500+ students for 48 hours of building, learning, and competing for $10k in prizes.",
    fullDescription:
      "Join us for the most anticipated coding event of the semester! The Annual Fall Hackathon is a 48-hour sprint where students from all backgrounds come together to build innovative solutions for real-world problems. Whether you're a seasoned developer or a first-time coder, there's a place for you here. This year's theme is Sustainable Tech for a Greener Campus. Participants will have access to mentors from top tech companies, unlimited coffee, snacks, and a chance to win over $10,000 in prizes.",
    capacity: 100,
    filled: 85,
    venue: "Innovation Hub, Engineering Block A, Level 3",
    address: "123 Campus Way, Innovation District, Engineering Wing",
    perks: "Certificate of participation included for all attendees.",
    attendees: 85,
  },
  {
    id: 2,
    title: "Sunset Mix & Mingle",
    category: "SOCIAL",
    date: "Oct 26",
    time: "6:00 PM",
    location: "University Quad",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80",
    popular: false,
    liked: false,
    description:
      "Unwind after a week of classes with free food, live music, and lawn games on the quad.",
    fullDescription:
      "Take a break from studies and join us for an evening of fun, food, and friendship! The Sunset Mix & Mingle is our most popular social event, featuring live DJ sets, yard games, and catered food trucks. Perfect for meeting new people and reconnecting with old friends.",
    capacity: 200,
    filled: 120,
    venue: "University Quad, Central Campus",
    address: "University Quad, Main Campus",
    perks: "Free food and beverages for all attendees.",
    attendees: 120,
  },
  {
    id: 3,
    title: "Leadership Accelerator",
    category: "CAREER",
    date: "Oct 28",
    time: "2:00 PM",
    location: "Student Union",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
    popular: true,
    liked: false,
    description:
      "A high-intensity workshop designed to help club leaders master project management.",
    fullDescription:
      "Designed for current and aspiring student leaders, the Leadership Accelerator is a full-day intensive workshop covering project management, conflict resolution, and strategic planning. Led by industry mentors, this workshop will give you the skills to lead your organization effectively.",
    capacity: 50,
    filled: 38,
    venue: "Student Union, Room 201",
    address: "45 Union Ave, Student Union Building",
    perks: "Certificate of completion and LinkedIn badge.",
    attendees: 38,
  },
  {
    id: 4,
    title: "Annual Spring Hackathon 2024",
    category: "COMPETITIVE",
    date: "May 15",
    time: "10:00 AM - 8:00 PM",
    location: "University Grand Hall",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&q=80",
    popular: true,
    liked: false,
    description:
      "A 10-hour sprint where students collaborate to build innovative solutions for real-world problems.",
    fullDescription:
      "Join us for the most anticipated coding event of the semester! The Annual Spring Hackathon is a 10-hour sprint where students from all backgrounds come together to build innovative solutions for real-world problems. Whether you're a seasoned developer or a first-time coder, there's a place for you here. This year's theme is Sustainable Tech for a Greener Campus. Participants will have access to mentors from top tech companies, unlimited coffee, snacks, and a chance to win over $5,000 in prizes.",
    capacity: 100,
    filled: 85,
    venue: "University Grand Hall",
    address: "123 Campus Way, Innovation District, Engineering Wing",
    perks: "Certificate of participation included for all attendees.",
    attendees: 85,
  },
  {
    id: 5,
    title: "AI & Machine Learning Summit",
    category: "ACADEMIC",
    date: "Nov 2",
    time: "9:00 AM",
    location: "Science Complex",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80",
    popular: false,
    liked: false,
    description:
      "Explore cutting-edge AI research with professors and industry professionals.",
    fullDescription:
      "A full-day academic symposium bringing together faculty, students, and industry experts to discuss the latest advances in artificial intelligence and machine learning. Feature presentations, panel discussions, and hands-on demos.",
    capacity: 150,
    filled: 90,
    venue: "Science Complex, Auditorium B",
    address: "Science Complex, 78 Research Blvd",
    perks: "Access to recorded sessions and research papers.",
    attendees: 90,
  },
  {
    id: 6,
    title: "Campus 5K Run",
    category: "SPORTS",
    date: "Nov 5",
    time: "7:00 AM",
    location: "Athletics Field",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    popular: false,
    liked: false,
    description:
      "Lace up and join hundreds of students for the annual charity 5K run around campus.",
    fullDescription:
      "The annual Campus 5K Run raises funds for student scholarships and is open to all fitness levels. The course takes runners through the most scenic parts of campus. Medals and refreshments for all finishers!",
    capacity: 300,
    filled: 210,
    venue: "Athletics Field, Track 1",
    address: "Athletics Complex, South Campus",
    perks: "Finisher medal and t-shirt for all participants.",
    attendees: 210,
  },
];
 
export default events;